kind: ConfigMap
apiVersion: v1
metadata:
  name: cd-jenkins-jenkins-jcasc-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/cd-jenkins-jenkins-jcasc-config
  uid: 5a1f90d1-8745-4470-93d5-0c20447baa66
  resourceVersion: '2056066'
  creationTimestamp: '2020-11-30T08:00:42Z'
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: cd-jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    cd-jenkins-jenkins-config: 'true'
    helm.sh/chart: jenkins-2.6.4
  annotations:
    meta.helm.sh/release-name: cd-jenkins
    meta.helm.sh/release-namespace: default
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2020-11-30T08:00:42Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:cd-jenkins-jenkins-config': {}
            'f:helm.sh/chart': {}
    - manager: k8saasapi
      operation: Update
      apiVersion: v1
      time: '2020-12-15T09:51:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:jcasc-default-config.yaml': {}
data:
  jcasc-default-config.yaml: |-
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        legacy
      disableRememberMe: false
      remotingSecurity:
        enabled: true
      mode: NORMAL
      numExecutors: 0
      projectNamingStrategy: "standard"
      markupFormatter:
        plainText
      clouds:
      - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          jenkinsUrl: "http://cd-jenkins:8080"
          jenkinsTunnel: "cd-jenkins-agent:50000"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "default"
          serverUrl: "https://kubernetes.default"
          podLabels:
          - key: "jenkins/cd-jenkins-jenkins-slave"
            value: "true"
          templates:
            - name: "default"
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://cd-jenkins.default.svc.cluster.local:8080"
                image: "jenkins/inbound-agent:4.3-4"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                runAsUser: 
                runAsGroup: 
                ttyEnabled: false
                workingDir: /home/jenkins
              idleMinutes: 0
              instanceCap: 2147483647
              label: "cd-jenkins-jenkins-slave "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              serviceAccount: "default"
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
            - name: "dind"
              containers:
              - name: "dind"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://cd-jenkins.default.svc.cluster.local:8080"
                image: "jenkins/inbound-agent:4.3-4"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                runAsUser: 
                runAsGroup: 
                ttyEnabled: false
                workingDir: /home/jenkins
              idleMinutes: 0
              instanceCap: 2147483647
              label: "cd-jenkins-jenkins-slave "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              serviceAccount: "default"
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override  
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    unclassified:
      location:
        adminAddress: 
        url: http://cd-jenkins:8080
